"""Curated software vocabulary used by ASR biasing and term normalization.

The source is grouped so future UI features can identify a likely technical
topic without loading an AI model on the latency-sensitive transcription path.
"""

from __future__ import annotations

import re


def _words(value: str) -> tuple[str, ...]:
    return tuple(part.strip() for part in value.split(",") if part.strip())


TOPIC_VOCABULARY = {
    "Python": _words("""python,cpython,pypy,interpreter,bytecode,pep8,virtualenv,venv,pip,
        poetry,setuptools,wheel,module,package,import,namespace,__init__,dunder methods,
        magic methods,object,class,inheritance,multiple inheritance,mro,polymorphism,
        encapsulation,abstraction,duck typing,dynamic typing,strong typing,mutable,immutable,
        list,tuple,set,dictionary,dict comprehension,list comprehension,generator,iterator,
        yield,decorator,closure,lambda,recursion,exception,try except,finally,context manager,
        with statement,file handling,serialization,pickle,json,threading,multiprocessing,
        concurrency,parallelism,asyncio,async,await,event loop,gil,garbage collection,
        reference counting,memory management,dataclass,pydantic,typing,type hints,mypy,
        pytest,unittest,mocking,flask,django,fastapi,sqlalchemy,orm,jinja2,requests,
        beautifulsoup,selenium python,logging,argparse,click,subprocess,os module,sys module,
        pathlib,datetime,itertools,functools,collections,deque,defaultdict,namedtuple"""),
    "Django": _words("""django,django framework,django orm,model,view,template,mvc,mvt,
        middleware,admin panel,migration,makemigrations,migrate,queryset,serializer,
        django rest framework,drf,csrf,csrf token,signals,forms,authentication,authorization,
        user model,permissions,groups,session,cookies,static files,media files,url routing,
        urls.py,views.py,models.py,templates,apps,settings.py,wsgi,asgi,gunicorn,uwsgi,
        debug toolbar,django shell,manage.py,superuser,django cache,memcached,redis cache,
        database router,fixtures,testing django,pytest django,factory boy,celery,task queue,
        background task,channels,websocket django,django signals,middleware chain,
        django security,password hashing,bcrypt,argon2,email backend,file upload,file storage,
        django storage,s3 django,custom user model,django auth,django filters,pagination,
        throttling,rate limiting,swagger drf,openapi django,permission classes,serializer fields"""),
    "AWS": _words("""aws,amazon web services,ec2,elastic compute cloud,s3,simple storage service,
        lambda,serverless,cloudwatch,iam,identity and access management,vpc,virtual private cloud,
        subnet,route table,internet gateway,nat gateway,security group,elastic load balancer,elb,
        application load balancer,network load balancer,autoscaling,ecs,elastic container service,
        eks,elastic kubernetes service,fargate,rds,relational database service,dynamodb,aurora,
        redshift,cloudfront,cdn,route53,dns,sns,sqs,ses,simple email service,kinesis,glue,athena,
        cloudformation,elastic beanstalk,waf,shield,inspector,secrets manager,parameter store,
        cloudtrail,backup,efs,elastic file system,fsx,batch,step functions,organizations,
        control tower,cognito,appsync,eventbridge,lightsail,codebuild,codepipeline,codedeploy,
        elasticache,opensearch,cloud9,outposts,global accelerator,direct connect,privatelink,
        storage gateway,transit gateway,config,x-ray,well architected"""),
    "API": _words("""api,application programming interface,rest,restful,graphql,grpc,soap,
        endpoint,http,https,request,response,json,xml,status code,crud,get,post,put,delete,patch,
        authentication,authorization,jwt,oauth,token,bearer token,refresh token,rate limiting,
        throttling,pagination,filtering,sorting,versioning,idempotent,stateless,webhook,
        callback url,swagger,openapi,postman,curl,headers,body,query parameter,path parameter,
        cookies,session,cors,csrf,ssl,tls,api gateway,proxy,reverse proxy,microservice api,
        monolith api,integration api,third party api,public api,private api,internal api,
        documentation,schema,api contract,api lifecycle,timeout,retry,caching,cache control,
        etag,content type,multipart,form data,file upload,file download,websocket api,
        streaming api,long polling,api monitoring,api analytics,load testing api,
        security testing api,api mocking,sandbox,rate limit header"""),
    "Database": _words("""database,dbms,rdbms,nosql,sql,mysql,postgresql,oracle,sqlite,mssql,
        mongodb,redis,cassandra,dynamodb,mariadb,cockroachdb,neo4j,couchdb,columnar database,
        document database,document store,key value store,column family,graph database,
        time series database,schema,table,row,column,primary key,foreign key,unique constraint,
        not null,constraint,index,indexing,composite index,clustered index,non clustered index,
        query,select,insert,update,delete,join,inner join,left join,right join,full join,
        aggregation,group by,having,order by,transaction,acid,consistency,isolation,durability,
        isolation level,read committed,serializable,replication,master slave,read replica,
        sharding,partitioning,horizontal partition,vertical partition,clustering,backup,restore,
        migration,etl,data warehouse,olap,oltp,trigger,stored procedure,function,view,
        materialized view,query optimization,query plan,execution plan,deadlock,locking,
        concurrency control,snapshot isolation,write ahead log,log shipping,failover,
        connection pooling,database driver,jdbc,odbc,orm,sql injection,data integrity,
        referential integrity,data consistency,big data storage,cold storage,hot storage,
        archiving,index scan,full scan"""),
    "Frontend": _words("""frontend,ui,ux,html,html5,css,css3,javascript,typescript,react,
        angular,vue,svelte,component,state management,redux,context api,hooks,useeffect,usestate,
        router,react router,spa,single page application,virtual dom,dom manipulation,
        responsive design,media query,flexbox,grid,box model,margin,padding,border,z-index,
        position,absolute,relative,sticky,animation,transition,keyframes,sass,less,tailwind,
        bootstrap,material ui,ant design,webpack,vite,babel,es6,es7,promise,async await,
        event handling,form validation,controlled components,uncontrolled components,
        accessibility,aria,seo,meta tags,favicon,progressive web app,pwa,service worker,
        local storage,session storage,fetch api,axios,lazy loading,code splitting,tree shaking,
        hydration,server side rendering,ssr,static site generation,jamstack,storybook,
        testing library,jest,cypress,playwright,frontend performance"""),
    "Backend": _words("""backend,server,application server,web server,business logic,
        service layer,controller,repository pattern,dependency injection,middleware,routing,
        rest api,graphql server,grpc service,monolith,microservices,service mesh,load balancing,
        reverse proxy,nginx,apache,gunicorn,uwsgi,node server,express,spring boot,django backend,
        flask backend,fastapi,authentication,authorization,jwt,oauth,session management,
        cookie handling,cors,csrf protection,input validation,serialization,deserialization,orm,
        sqlalchemy,hibernate,database connection pooling,transaction management,caching,
        redis cache,memcached,rate limiting,throttling,pagination,filtering,sorting,
        background job,task queue,celery,rabbitmq,kafka,message broker,event driven architecture,
        webhook handling,file upload,file storage,s3 storage,blob storage,error handling,
        exception handling,logging,monitoring,health check,graceful shutdown,timeout,retry logic,
        idempotency,scalability,horizontal scaling,vertical scaling,high availability,failover,
        circuit breaker,bulkhead pattern,api gateway,service discovery,load testing,
        performance tuning,profiling,memory leak,thread safety,parallel processing,
        async processing,synchronous processing,data validation,schema validation,json schema"""),
    "DevOps": _words("""devops,ci/cd,continuous integration,continuous deployment,pipeline,
        build pipeline,release pipeline,jenkins,gitlab ci,github actions,circleci,travis ci,
        azure devops,deployment,rolling deployment,blue green deployment,canary deployment,
        infrastructure as code,iac,terraform,ansible,chef,puppet,docker,container,
        containerization,kubernetes,k8s,pod,service,deployment yaml,helm,orchestration,
        auto scaling,load balancer,reverse proxy,nginx,apache,linux,bash,shell scripting,
        cron job,systemd,cloud computing,aws,azure,gcp,monitoring,logging,prometheus,grafana,
        elk stack,logstash,elasticsearch,kibana,alerting,incident response,observability,metrics,
        tracing,uptime monitoring,health check,server provisioning,vm,virtual machine,vagrant,
        hypervisor,networking,firewall,vpn,load testing,performance monitoring,
        resource utilization,cpu usage,memory usage,disk usage,backup,restore,disaster recovery,
        high availability,failover,replication,cdn,edge computing,security patching,
        secrets management,vault,key vault,certificate management,ssl,tls,domain management,
        dns,reverse dns,port forwarding,container registry,docker hub,artifact repository,nexus,jfrog"""),
    "Operating System": _words("""operating system,os,linux,windows,unix,kernel,user space,
        system call,process,thread,multithreading,multiprocessing,context switch,scheduler,
        cpu scheduling,priority scheduling,round robin,deadlock,starvation,semaphore,mutex,
        spinlock,critical section,race condition,memory management,virtual memory,paging,
        segmentation,swap space,heap,stack memory,buffer overflow,file system,inode,
        directory structure,disk scheduling,io scheduling,interrupt,device driver,process state,
        zombie process,orphan process,fork,exec,ipc,inter process communication,pipe,socket,
        shared memory,message queue,signals,signal handling,virtualization,hypervisor,
        containerization,namespaces,cgroups,boot process,bios,uefi,kernel modules,
        loadable modules,daemon,cron,systemd,shell,bash,terminal,tty,environment variable,
        path variable,permissions,chmod,chown,file descriptor,mount,umount,swap,cache,
        page fault,thrashing,cpu affinity,load average,resource allocation,
        deadlock prevention,deadlock avoidance,bankers algorithm"""),
    "Testing": _words("""testing,software testing,unit testing,integration testing,
        system testing,functional testing,non functional testing,regression testing,
        smoke testing,sanity testing,acceptance testing,uat,automation testing,manual testing,
        test case,test scenario,test suite,test plan,test strategy,bug report,defect lifecycle,
        test coverage,code coverage,branch coverage,statement coverage,pytest,unittest,nose,
        jest,mocha,chai,cypress,selenium,webdriver,playwright,puppeteer,robot framework,
        test automation framework,page object model,pom,mocking,stubbing,test doubles,fixture,
        setup,teardown,assertion,parameterized test,data driven testing,
        behavior driven development,bdd,tdd,gherkin,cucumber,api testing,postman,swagger,newman,
        load testing,performance testing,stress testing,soak testing,jmeter,locust,k6,
        security testing,penetration testing,vulnerability scanning,static testing,dynamic testing,
        white box testing,black box testing,grey box testing,boundary value analysis,
        equivalence partitioning,exploratory testing,usability testing,compatibility testing,
        cross browser testing,mobile testing,device testing,test environment,staging environment,
        production testing,test report,defect tracking,jira,bugzilla,test metrics,
        test automation script,ci testing,cd testing"""),
    "Azure Cloud": _words("""azure,microsoft azure,azure portal,resource group,subscription,
        tenant,azure active directory,aad,role based access control,rbac,azure vm,virtual machine,
        vm scale set,azure app service,azure functions,serverless,azure kubernetes service,aks,
        azure container registry,acr,azure blob storage,table storage,queue storage,
        azure sql database,cosmos db,azure database for mysql,azure database for postgresql,
        data factory,data lake,synapse analytics,azure devops,pipeline,release pipeline,
        azure monitor,log analytics,application insights,azure load balancer,application gateway,
        traffic manager,virtual network,vnet,subnet,network security group,nsg,expressroute,
        vpn gateway,private endpoint,azure firewall,azure bastion,azure key vault,managed identity,
        azure policy,blueprint,azure backup,site recovery,disaster recovery,availability set,
        availability zone,auto scaling,autoscale rule,azure cli,powershell azure,arm template,
        bicep,terraform azure,logic apps,event grid,event hub,service bus,azure storage account,
        azure disk,azure file share,azure dns,azure cdn,azure front door,azure arc,
        azure lighthouse,cost management,billing,governance,azure security center,
        defender for cloud,azure sentinel,azure automation,runbook"""),
    "Data Science": _words("""data science,data analysis,data analytics,pandas,numpy,
        matplotlib,seaborn,plotly,statistics,probability,mean,median,mode,variance,
        standard deviation,correlation,covariance,hypothesis testing,p value,confidence interval,
        data cleaning,data wrangling,feature engineering,feature scaling,normalization,
        standardization,regression,linear regression,logistic regression,classification,
        clustering,k means,hierarchical clustering,dbscan,decision tree,random forest,
        gradient boosting,xgboost,lightgbm,catboost,support vector machine,svm,naive bayes,knn,
        dimensionality reduction,pca,tsne,lda,model training,model evaluation,accuracy,precision,
        recall,f1 score,roc curve,auc,confusion matrix,cross validation,k fold,overfitting,
        underfitting,bias variance tradeoff,hyperparameter tuning,grid search,random search,
        deep learning,neural network,cnn,rnn,lstm,transformer,nlp,natural language processing,
        tokenization,stemming,lemmatization,sentiment analysis,computer vision,image processing,
        object detection,segmentation,time series forecasting,anomaly detection,
        recommendation system,scikit learn,tensorflow,keras,pytorch,data visualization,
        dashboard,tableau,power bi,big data,hadoop,spark"""),
}

# Preserve insertion order while removing terms repeated across categories.
DEFAULT_TECHNICAL_VOCABULARY = tuple(dict.fromkeys(
    word for words in TOPIC_VOCABULARY.values() for word in words))


def detect_technical_topics(text: str) -> tuple[str, ...]:
    """Return matching topics using token boundaries, not substring guesses."""
    normalized = re.sub(r"[^\w+#./-]+", " ", text.casefold())
    padded = f" {normalized} "
    matches = []
    for topic, words in TOPIC_VOCABULARY.items():
        if any(f" {word.casefold()} " in padded for word in words):
            matches.append(topic)
    return tuple(matches)

